import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex bg-canvas h-screen'>
					<div className='min-h-0 flex-1 overflow:hidden w-[200px]'>
						<Sidebar />
					</div>
					<div className='w-[calc(100vw-200px)]'>{children} </div>
				</div>
			</body>
		</html>
	)
}
